.\" Manpage for single-HTTP
.\" Contact vivek@nixcraft.net.in to correct errors or typos.
.TH man 8 "07 Feb 2019" "0.7" "nsingle-HTTP man page"
.SH NAME
single-HTTP \- A full http server
.SH SYNOPSIS
Usage: %s [-v] [-h] [-V] [-i <database>] [-d[table]] [-l <filepath>] [-s <configuration file>] [-u <unsigned int>] [-g <unsigned int>] [-c <unsigned int>]
.SH DESCRIPTION
nuseradd is high level shell program for adding users to LDAP server.  On Debian, administrators should usually use nuseradd.debian(8) instead.
.SH OPTIONS
The nuseradd does not take any options. However, you can supply username.
.SH SEE ALSO
None.
.SH BUGS
No known bugs.
.SH AUTHOR
Elliott Sobek (elliottsobek@gmail.com)
